export const home = [
  {
    logo: "Datz Press",
    type: "New Books",
    title_en: "PERU",
    subtitle_en: "Linda Connor",
    title_ko: "PERU",
    subtitle_ko: "린다 코너 ",
    url: "/publication/2019_peru",
    image: "/Main/01/01.jpg",
  },
  {
    logo: "Datz Press",
    type: "New Books",
    title_en: "PERU",
    subtitle_en: "Linda Connor",
    title_ko: "PERU",
    subtitle_ko: "린다 코너 ",
    url: "/publication/2019_peru",
    image: "/Main/01/02.jpg",
  },
  {
    logo: "Datz Press",
    type: "New Books",
    title_en: "Here to Stay",
    subtitle_en: "Yoonsuk Kim",
    title_ko: "우리는 이곳에서",
    subtitle_ko: "김윤숙",
    url: "/publication/2020_here-to-stay",
    image: "/Main/01/03.jpg",
  },
  {
    logo: "Datz Press",
    type: "New Books",
    title_en: "LANDFALL",
    subtitle_en: "Sal Taylor Kydd",
    title_ko: "LANDFALL",
    subtitle_ko: "살 테일러 키드",
    url: "/publication/2020_landfall",
    image: "/Main/01/04.jpg",
  },
  {
    logo: "Datz Press",
    type: "New Books",
    title_en: "Nothing Will Ever be the Same Again(SE)",
    subtitle_en: "Amanda Marchand",
    title_ko: "모두 다른 하나의 순간들(SE) ",
    subtitle_ko: "아만다 마찬드",
    url:
      "/publication/2019_nothing-will-ever-be-the-same-again_se",
    image: "/Main/01/05.jpg",
  },
  {
    logo: "Datz Press",
    type: "New Books",
    title_en: "Offerings(SE)",
    subtitle_en: "Mary Daniel Hobson",
    title_ko: "Offerings(SE)",
    subtitle_ko: "메리 다니엘 홉슨",
    url: "/publication/2019_offerings_se",
    image: "/Main/01/06.jpg",
  },
  {
    logo: "Datz Museum of Art",
    type: "Current Exhibition",
    title_en: "REFLECTION",
    subtitle_en: "2020.9.5 - 2020.11.22",
    title_ko: "REFLECTION",
    subtitle_ko: "2020.9.5 - 2020.11.22",
    url: "/exhibition/2020_reflection",
    image: "/Main/02/01.jpg",
  },
  {
    logo: "Datz Museum of Art",
    type: "Current Exhibition",
    title_en: "REFLECTION",
    subtitle_en: "2020.9.5 - 2020.11.22",
    title_ko: "REFLECTION",
    subtitle_ko: "2020.9.5 - 2020.11.22",
    url: "/exhibition/2020_reflection",
    image: "/Main/02/02.jpg",
  },
  {
    logo: "Datz Museum of Art",
    type: "Current Exhibition",
    title_en: "REFLECTION",
    subtitle_en: "2020.9.5 - 2020.11.22",
    title_ko: "REFLECTION",
    subtitle_ko: "2020.9.5 - 2020.11.22",
    url: "/exhibition/2020_reflection",
    image: "/Main/02/03.jpg",
  },
  {
    logo: "Datz Museum of Art",
    type: "Current Exhibition",
    title_en: "REFLECTION",
    subtitle_en: "2020.9.5 - 2020.11.22",
    title_ko: "REFLECTION",
    subtitle_ko: "2020.9.5 - 2020.11.22",
    url: "/exhibition/2020_reflection",
    image: "/Main/02/04.jpg",
  },
  {
    logo: "D'Ark Room",
    type: "Current Exhibition",
    title_en: "Art of Imagination",
    subtitle_en: "2020.8.7 - 2020.10.31",
    title_ko: "상상의 기술",
    subtitle_ko: "2020.8.7 - 2020.10.31",
    url: "/exhibition/2020_art-of-imagination",
    image: "/Main/02/05.jpg",
  },
  {
    logo: "D'Ark Room",
    type: "Current Exhibition",
    title_en: "Art of Imagination",
    subtitle_en: "2020.8.7 - 2020.10.31",
    title_ko: "상상의 기술",
    subtitle_ko: "2020.8.7 - 2020.10.31",
    url: "/exhibition/2020_art-of-imagination",
    image: "/Main/02/06.jpg",
  },
  {
    logo: "D'Ark Room",
    type: "Past Event",
    title_en: "From South Korea to NYPL: Datz Press",
    subtitle_en: "2019.9.25",
    title_ko: "From South Korea to NYPL: Datz Press",
    subtitle_ko: "2019.9.25",
    url: "/event/2019_nypl",
    image: "/Main/03/01.jpg",
  },
  {
    logo: "Datz Press",
    type: "Past Event",
    title_en: "Nature, Conversations",
    subtitle_en: "2020.4.20 - 2020.6.12",
    title_ko: "자연, 그리고 우리가 이어갈 대화",
    subtitle_ko: "2020.4.20 - 2020.6.12",
    url: "/event//2019_material-memory",
    image: "/Main/03/02.jpg",
  },
  {
    logo: "Datz Press",
    type: "Past Event",
    title_en: "Material, Memory",
    subtitle_en: "2019.9.28 - 2019.12.31",
    title_ko: "물질 기억: Material, Memory",
    subtitle_ko: "2019.9.28 - 2019.12.31",
    url: "/event/2020_nature-conversations",
    image: "/Main/03/03.jpg",
  },
];
