export const events = [
  {
    id: 1,
    type: "Artist Talk / Lecture",
    date: "2020.8.7",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#24 Round Table ‘Material, Intersections’",
    body_en:
      'As a combined event with the exhibition ‘Art of Imagination’, first FNL of this year, the round table ‘Material, Intersections’ was held in D’ark Room.  Young korean artists, Hyunjeong Kimbak, Meen Yea Oh, Hyunseon Son and Hyejin Jo talked about the process of art making. Hyunjeong Kimbak(Photography) turns the imagination of reassembling images and materials into material again. Hyunseon Son(Painting) explores the surface of a material that is not directly related to its original functional purpose. Hyejin Jo(Installation) questions the value of an object’s essential shape and reconstructs it into space. . In Meen Yea Oh expanded her imagination by introducing an art book with its original function "Reading" erased. It was a time to take a deeper look at the artist\'s inspiration in everyday life, interpreted through visual language and creative thinking. In the exhibition ‘Art of Imagination’, you can see the works of four artists, as well as artist books from various countries selected by Datz.\n \nFeaturing: \nHyunjeong Kimbak(Artist), Hyunseon Son(Artist), Meen Yea Oh(Artist), Hyejin Jo(Artist)\n \nLead by Minkyung Lee(Project Manager) ',
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#24 라운드 테이블 <물질, 교차점>",
    body_ko:
      "전시 <상상의 기술Art of Imagination>의 연계 행사로 올해 첫 FNL인 라운드 테이블 <물질, 교차점>이 다크룸에서 열렸습니다. 한국의 젊은 예술가, 김박현정, 손현선, 오민예, 조혜진은 사물로부터 받은 영감이 작품으로 거듭나기까지의 과정에 대해 이야기를 나누었는데요. 김박현정 작가는 마치 회화작가가 페인팅을 하듯 자신이 채집한 이미지를 회화적 사진으로 변환하였고, 손현선 작가는 영감받은 사물을 통해 상상과 해석의 여지에 주목하여 그려낸 작품들에 대해 설명하였습니다. 조혜진 작가는 사물의 본질적 형태가 보여주는 가치를 질문하며 이를 공간 속에 패턴으로 재구성하였고, 오민예 작가는 책 본연의 기능 ‘읽기’가 지워진 상태의 아트북을 선보임으로써 상상의 여지를 확장하였습니다. 일상 가운데 예술가의 영감이 시각 언어와 창의적 사유를 통해 해석된 깊이 들여다볼수 있는 시간이었습니다. 다크룸과 디프론트 스페이스에서 진행되고 있는 전시 <상상의 기술>에서는 네명의 작가의 작품들과 함께 닻이 선정한 다양한 나라의 아티스트북을 함께 볼 수 있습니다. \n \n참여작가: 김박현정, 손현선, 오민예, 조혜진\n진행: 이민경(프로젝트 매니저)",
    images: [
      "/Event/01/01.jpg",
      "/Event/01/02.jpg",
      "/Event/01/03.jpg",
      "/Event/01/04.jpg",
      "/Event/01/05.jpg",
      "/Event/01/06.jpg",
      "/Event/01/07.jpg",
      "/Event/01/08.jpg",
      "/Event/01/09.jpg",
      "/Event/01/10.jpg",
      "/Event/01/11.jpg",
    ],
  },
  {
    id: 2,
    type: "Exhibition",
    date: "2020.4.20 - 2020.6.12",
    place_en: "Space B-E, the gallery of YUNHYUN Trading",
    title_en: "Nature, Conversations",
    body_en:
      "Datz Press participated in the exhibition organized by Space B-E, the gallery of YUNHYUN Trading.The project was organized with the publications of Datz Press, inspired by Datz Museum of Art's exhibition ‘From Walden’ in 2016 and magazine Git vol.8 with the same title. Now that the world is gripped by anxiety and fear from the virus, the exhibition asks , ‘what is human life’, ‘what is the free human path’, and ‘what is empathy with nature?’. Already 170 years ago, a thinker and writer Henry David Thoreau began his own adventure of living alone in Lake Walden, asking himself the above questions through deep reflection on human beings, nature, humans and society. In the exhibition, it is seriously considered what enlightenment Thoreau, who practiced an unowned life in Nature and Lake Walde and what challenges we faced. In ‘Nature, Conversations’, we discussed human intellect and nature inspiration with photographers Eliot Porter, David Ellingsen, Sangyon Joo, Kirk Crippens & Gretchen Lemaistre and with plants works of Teal Table, guide you to a different world of thoughts. The exhibition ‘Nature, Conversations’ reorganizes part of Datzr Museum’s exhibition in the space B-E space, and continues the story of what is happening at the same time through the publication of Datz Press.",
    place_ko: "Space B-E, 윤현상재",
    title_ko: "자연, 그리고 우리가 이어갈 대화",
    body_ko:
      "닻프레스는 윤현상재의 갤러리, Space B-E에서 주최한 전시에 참여하였습니다. 이 기획은 2016년 닻미술관의 전시 <월든으로부터>와 동명의 제목을 가진 매거진 깃 8호에 영감을 받아 닻프레스의 출판물과 함께 구성되었습니다. 바이러스로 온 세계가 불안과 공포에 휩싸인 지금 이 전시를 통해 ‘무엇이 인간다운 삶인지’, ‘자유로운 인간의 길은 무엇인지’, ‘자연과의 공감은 무엇인지’ 질문합니다. 이미 170여 년 전 사상가이자 문학가인 헨리 데이비드 소로우는 월든이라는 호수에 홀로 거주하는 모험을 시작하며 인간과 자연, 인간과 사회에 대한 깊은 성찰을 통해 스스로 위와 같은 질문을 던졌습니다. 대자연(Nature), 호수 월든(Walden)에서 무소유의 삶을 실천한 소로우가 얻은 깨달음이 어떤 것인지 가늠해보며 우리에게 당면한 과제를 진지하게 고민합니다. 전시 <Nature, Conversations:자연, 그리고 우리가 이어갈 대화>는 사진작가 엘리엇 포터, 데이비드 엘링슨, 주상연, 커크 크리펜스&그레첸 르마이스트레 등과 함께 인간의 지성과 자연의 영감에 대해 논하며, 틸테이블의 식물 작업과 함께 또 다른 사유의 공간으로 안내합니다. 닻미술관의 전시 일부를 스페이스 B-E 공간에 재구성하고, 자연과 인간의 관계를 예술로 창작해 온 닻프레스의 출판물을 통해 동시대에 벌어지고 있는 현상에 대한 이야기를 이어갑니다. ",
    images: [
      "/Event/02/01.jpg",
      "/Event/02/02.jpg",
      "/Event/02/03.jpg",
      "/Event/02/04.jpg",
      "/Event/02/05.jpg",
      "/Event/02/06.jpg",
      "/Event/02/07.jpg",
      "/Event/02/08.jpg",
      "/Event/02/09.jpg",
      "/Event/02/10.jpg",
    ],
  },
  {
    id: 3,
    type: "Artist Talk / Lecture",
    date: "2019.11.1",
    place_en: "Cafe Dotz, Datz Museum of Art",
    title_en: "Exhibition Opening event: ‘Farm to Table’",
    body_en:
      "As an opening event, 'Farm to Table’ is organized by Seongyeon Jo, who participated in the exhibition ‘Synesthesia: The Space Between’. Seongyeon Jo investigated and analyzed the process of growth and extinction of seeds for a long time with the attitude of a botanist, since she began to experience life as an urban farmer a few years ago. Jo has worked on sophisticated and static photography by expanding the viewpoint, noticing the order in nature and materiality as she has cultivated her own crops. The ‘farm to table’ event consists of the table that contains crops grown by the artist. The event prepared by artist Jo was not only  visually beautiful by reproducing the cycle of nature, but also integrated the process of communication with other senses, including sharing with the participants.",
    place_ko: "닻미술관, 카페 돛",
    title_ko: "전시 오프닝 행사: ‘팜 투 테이블’",
    body_ko:
      "‘팜 투 테이블’은 <다른 감각들의 공간Synesthesia: The Space Between>전시 오프닝 이벤트로 전시에 참여한 조성연 작가가 기획하였습니다. 아티스트북 「지고 맺다Arranging Life」에서 씨앗이 발아하는 성장과정과 소멸의 과정을 식물학자처럼 조사하고, 분석하는 등 오랜 기간 동안 느린 태도로 관찰하며 세련되고 정적인 조형의 사진작업을 해온 조성연은 몇 해 전부터 도시농부로서의 삶을 체험하기 시작했습니다. 몸소 작물을 경작하며 자연의 이치와 질서, 그리고 물질성을 경험한 작가의 시야는 자연스레 확장되어 쓸모없이 버려지고 죽은 듯 보이는 것들에 숨결을 불어 넣었습니다. ‘팜 투 테이블’ 이벤트는 작가가 직접 재배한 농작물로 다채로운 시감각을 구성해 테이블에 올려냅니다.\n조성연 작가가 준비한 이벤트는 자연과 생성과 소멸의 순환 과정을 테이블위에 아름답게 재현해 시각적으로 아름다울 뿐만 아니라 참여자들과 함께 나누는 과정을 포함해 다른 감각들과 소통의 과정이 융화된 이벤트였습니다.\n",
    images: [
      "/Event/03/01.jpg",
      "/Event/03/02.jpg",
      "/Event/03/03.jpg",
      "/Event/03/04.jpg",
      "/Event/03/05.jpg",
      "/Event/03/06.jpg",
      "/Event/03/07.jpg",
    ],
  },
  {
    id: 4,
    type: "Exhibition",
    date: "2019.9.28 - ",
    place_en: "Outside Gallery, North Adams, MA, USA",
    title_en: "Material, Memory",
    body_en:
      "Outside is a storefront gallery for contemporary art and design located in downtown North Adams, MA. Outside is dedicated to providing a platform for artists and designers to develop and realize a complete project or idea, and to providing all exhibitions free and open to the public. Central to this mission is an interest in expanding and showcasing the intersections between art, architecture, design and fabrication. Outside presents and publishes focused exhibitions of early to mid career artists, designers and makers. \nThrough Material Memory, Outside presented the exhibition Of Datz Press, which has integrated photography, design, exhibition space, and publishing with a system that plans various contents and produces beautiful hand-made books.",
    place_ko: "Outside Gallery, 미국 매사추세츠 노스 아담스",
    title_ko: "물질 기억: Material, Memory",
    body_ko:
      "미국 매사추세츠 작은 도시 노스 아담스에 위치한 아웃사이드 갤러리(Outside Gallery)에서 닻프레스의 출판물이 초청된 <물질 기억: Material, Memory> 전이 9월 28일부터 진행되고 있습니다. 아웃사이드 갤러리는 Mass MoCA라는 큰 미술관과 대학이 위치해 뉴욕이나 대도시가 아닌 아웃사이드에 있다는 약점을 실력과 진정성으로 극복하고 스스로의 색을 만들어가고 있는 비영리 전시공간입니다. 디렉터인 Mandy Johnson과 James Jarzynieki는 건축가 출신으로 예술과 건축, 디자인, 공예 사이의 특별한 교차점을 주목하여 운영하고 있습니다. 3년 전 뉴욕 북 페어를 통해 만난 그들은 직접 다양한 컨텐츠를 기획하고 아름다운 책을 제작하는 시스템을 갖추어 사진과 디자인 및 전시공간과 출판을 접목해 온 닻프레스에게 전시를 제안하였습니다.\n 닻프레스는 전시장 가운데 예술가의 책을 직접 손으로 만드는 수공 제작과정을 영상으로 보여주고 출판물들을 시각과 촉각적으로 경험할 수 있는 기회를 제공함으로 많은 사람들의 관심을 이끌어냈습니다. 물질의 기억 전을 통해 예술과 디자인, 출판의 영역 안에서 다원적으로 해석이 가능할 수 있음을 보여주었습니다. 닻프레스의 출판물들이 예술품으로써 초대되었다는 데 그 의미가 있습니다.",
    images: [
      "/Event/04/01.jpg",
      "/Event/04/02.jpg",
      "/Event/04/03.jpg",
      "/Event/04/04.jpg",
      "/Event/04/05.jpg",
      "/Event/04/06.jpg",
      "/Event/04/07.jpg",
      "/Event/04/08.jpg",
    ],
  },
  {
    id: 5,
    type: "Artist Talk / Lecture",
    date: "2019.9.25",
    place_en: "The New York Public Library, Wachenheim Trustees Room",
    title_en: "From South Korea to NYPL: Datz Press",
    body_en:
      "“Datz Press understands and responds sensitively to what an artist is trying to imply, making it near perfection through a delicate process. The only publisher that can fully digest the spirit of my work for 30 years and deliver all of my photos is the Datz Press.” _Lonnie Graham\n \nThe New York Public Library(NYPL), one of the world’s four largest libraries, decided to own the entire publication of Datz Press and hosted the lecture on September 25 under the title ‘From South Korea to NYPL: Datz Press’. Sangyon Joo, the head of Datz Press and Datz Museum of Art, along with three artists, Amanda Marchand(photographer/writer), Minny Lee(photographer/poet), and Lonnie Graham(photographer/professor at Pennsylvania State University).\n \nThe lecture, which began with the greeting of Sangyon Joo, described the establishment background of Datz Museum of Art and Datz Press, the space that embodies the merits of exhibitions and books in an effective way, introduced the project space D’Ark Room, where the space that communicates with the public. \n \nAmanda Marchand, Minny Lee and Lonnie Graham had time to introduce their books published in Datz Press. The lecture is the significant event to introduce Datz Press to book lovers and the sponsors of the public library, with the NYPL’s collection which Datz Press’ publications are included.",
    place_ko: "뉴욕 공립도서관, Wachenheim Trustees Room",
    title_ko: "From South Korea to NYPL: Datz Press",
    body_ko:
      "“닻프레스는 예술가가 구현하고자 하는 바를 깊이 이해하며 민감하게 반응하여 섬세한 공정을 통해 완벽에 가깝게 실현합니다. 30년간의 제 작업의 정신을 온전히 소화하여 책으로 구현할 수 있고, 저의 모든 사진을 건내줄 수 있는 출판사는 닻프레스밖에 없습니다.” _로니 그래험\n \n세계 4대 도서관의 하나인 뉴욕 공립도서관(NYPL)은 닻프레스의 전 출판물의 소장을 결정하고 지난 9월 25일 <From South Korea to NYPL: Datz Press>라는 제목으로 강연을 주최하였습니다. 주 강연자로 닻프레스와 닻미술관의 주상연 대표와 세 명의 작가 아만다 마찬드(사진가), 미니 리(사진가, 시인), 로니 그래험(사진가, 펜실바니아 주립대 교수)이 함께 했습니다. \n \n주상연 대표의 인사로 시작된 강연은 닻미술관과 닻프레스의 설립 배경을 설명하며, 전시와 책의 장점을 효과적인 방법으로 구현하는 공간인 닻미술관과 출판사 닻프레스, 북 메이킹 스튜디오 닻북스, 책들로 대중들과 소통하는 공간이 프로젝트 스페이스 다크룸을 소개했습니다. 아만다 마찬드, 미니 리, 로니 그래험은 닻프레스와 함께 협업한 자신의 책 「모두 다른 하나의 순간들Nothing Will Ever be the Same Again」, 「Million Years」, 「세계와의 대화A Conversation with the World」을 소개하였습니다. 이번 행사는 뉴욕 공립도서관이 닻프레스의 전 출판물을 소장함으로 많은 책 애호가들과 공립도서관의 후원자들에게 닻프레스를 소개하는데 의미가 있었습니다.",
    images: ["/Event/05/01.jpg", "/Event/05/02.jpg", "/Event/05/03.jpg"],
  },
  {
    id: 6,
    type: "Book Fair",
    date: "2019.9.20 - 2019.9.22",
    place_en: "Printed Matter, MoMA PS 1",
    title_en: "NY ART BOOK FAIR 2019",
    body_en:
      "The NY Art Book Fair (NYABF) was held at MoMA PS1 in Long Island City and 369 organizations from 31 countries participated. Every year, more than 40,000 visitors, including book and art lovers, collectors, artists and art experts gather for this event. NY Art Book Fair is the place where people experiment by forming a community centered on books and interacting with the possibilities of various art publications. Datz Press, the only Korean publisher to participate for four consecutive years, received a positive response by introducing more than 30 publications, including 10 artist books/art books published in 2019. \n\nOne of the biggest achievements of consistently participating in the book fair over the past four years is that the entire publication of Datz Press gets included in the collection of New York Public Library and International Center of Photography(ICP).\n",
    place_ko: "Printed Matter, MoMA PS 1",
    title_ko: "뉴욕 아트북 페어 2019 ",
    body_ko:
      "올해 15년째인 뉴욕 아트북페어(NY Art Book Fair)는 롱아일랜드의 모마(MoMA) PS1에서 개최되어 31개국 369개의 기관에서 참가하였습니다. 매해 도서 및 예술애호가, 수집가, 예술가, 예술계 전문가를 포함한 4만 명 이상의 관람객들이 모여드는 행사로 책을 중심으로 커뮤니티를 형성하며 다양한 예술출판의 가능성을 교류하며 실험하는 현장입니다. 아시아의 14개 출판사 중 유일하게 한국에서 4년동안 참여 중인 닻프레스는 올해 출판한 10종의 아티스트북 및 아트북을 포함한 서른 여종의 출판물 선보이며 좋은 반응을 얻었습니다.\n \n지난 4년간 꾸준히 북페어에 참여한 가장 큰 성과 중 하나는 올해 뉴욕 공립도서관(NYPL)과 국제사진센터(ICP)에서 닻프레스의 전 출판물의 소장을 결정했다는 점 입니다. 이를 축하하는 공식행사이자 닻프레스와 닻프레스 출판 작가들의 강연인 <From South Korea to NYPL: Datz Press>가 뉴욕 공립도서관에 잇따라 열렸습니다. 이는 지난 10년간 닻프레스가 발간하고 출판한 책의 예술적이고 보존적인 가치를 국제적으로 인정받았다는데 그 의미가 더욱 더 깊습니다.",
    images: [
      "/Event/06/01.jpg",
      "/Event/06/02.jpg",
      "/Event/06/03.jpg",
      "/Event/06/04.jpg",
      "/Event/06/05.jpg",
    ],
  },
  {
    id: 7,
    type: "Artist Talk / Lecture",
    date: "2019.9.6",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#23 Artist Talk ‘Photography?’",
    body_en:
      "To celebrate the publication of Alan Eglinton's ‘poems,’ we hosted an artist talk. Alan Eglinton created a new story by combining photographic images with poetry. He shared stories about his work process which involved interactions between awakened synesthesia. It was time to have a deep understanding of Eglinton’s art world by listening to the story of the photo book ‘Only the fires says',a collection of photos taken without planning and ‘Yes, No, Maybe’, the image works with the poems dedicated to the artist’s wife.\nIt was a time for us to feel the artist’s images which were made through the process of focusing on emotions, senses, and stimuli.\n \nFeaturing: Alan Eglinton(Photographer)\n",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#23 아티스트 토크 <Photography?>",
    body_ko:
      "알란 에글린튼의 「poems」 출판을 기념하여 아티스트 토크를 진행하였습니다. 사진 이미지와 시 언어의 결합을 통해 새로운 이야기를 만들어내는 작업 과정과 공감각적인 직관을 일깨우는 그간의 작업에 대한 이야기를 들을 수 있었습니다. 계획하지 않고 찍어온 사진들을 모아 만들게 된 사진집 「Only the fires says」에 대한 진솔한 이야기와 작가의 아내에게 헌정하는 시와 이미지 작업 ‘Yes, No, Maybe’ 대한 이야기들을 들으며 작가의 작품세계를 깊이 이해하는 시간을 가졌습니다. 감정과 감각, 자극들에 집중하는 과정을 거쳐 만들어진 이미지들을 조금 더 가까이 느낄 수 있었던 시간이었습니다.\n \n참여작가: 알란 에글린튼",
    images: [
      "/Event/07/01.jpg",
      "/Event/07/02.jpg",
      "/Event/07/03.jpg",
      "/Event/07/04.jpg",
      "/Event/07/05.jpg",
      "/Event/07/06.jpg",
    ],
  },
  {
    id: 8,
    type: "Artist Talk / Lecture",
    date: "2019.8.23",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#22 Book Talk ‘Interpreting Text in Typography’",
    body_en:
      "Here's the 22nd FNL talking about delivering the story about typography. Prior to Hyunmee Kimi's book talk,we heard about Xianlu Yi’s artist book ‘Grass, Kim Su-yong’ as an intro book talk. Yi talked about how the typography art book, which he created during a class of Kim Hyunmee, became published through collaboration with Datz Press. Hyunmee Kim talked about how her interest started with typography that visually conveys text and accomplished with studying deeply with the possibility of typography. Kim shared the story of making process for typography books: ‘ODE TO TYPOGRAPHY’, initially created through the process of understanding the visual forms and vocabulary of words in early stage: TYPE LIBRARY’, a new book published with 62 typefaces and commentary: ‘HEART SUTRA’. \nIn the <Book of Lights> exhibition,  Dark Room, you can see the works of Hyunmee Kim and Xianlu Yi.\n \nFeaturing: Hyunmee Kim(Designer), Xianlu Yi(Designer/Intro)",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#22 북토크 <타이포그래피로 텍스트 해석하기>",
    body_ko:
      "타이포그래피로 텍스트를 전달하는 작업에 대한 이야기를 나누었던 스물 두 번째 FNL의 모습입니다. 김현미 작가의 북토크에 앞서 인트로 북토크로 이현노 작가의 아티스트북 「풀, 김수영」에 대한 이야기를 들었습니다. Sadi에 다니던 학생 시절, 스승이던 김현미 작가의 수업을 통해 만들었던 타이포그래피 아트북이 닻프레스와 협업을 통해 ‘출판’하게 된 과정의 이야기를 들을 수 있었습니다.\n \n김현미 작가님의 북토크는 시각적으로 텍스트를 전달하는 타이포그래피 작업에 대한 관심에서부터 그 가능성을 고찰하고 공부했던 단계적인 강의로 ‘타이포그래피’에 대한 이해를 높이고 배울 것이 많은 시간이었습니다. 초기에 단어가 가진 시각적인 형태와 어휘 등을 이해하는 과정을 거치며 만들어진 닻프레스의 출판물 「ODE TO TYPOGRAPHY」와 「반야심경」에 대한 이야기와 함께 62개의 서체와 해설이 담겨 출판된 신간 「TYPE LIBRARY」를 펼쳐보며 아트북으로 만들게 된 과정도 나누었습니다. 다크룸에서 진행되고 있는 <빛들의 책> 전시에서는 김현미 작가와 이현노 작가의 작품을 볼 수 있습니다.\n \n참여작가: 김현미, 이현노(인트로 강연)",
    images: [
      "/Event/08/01.jpg",
      "/Event/08/02.jpg",
      "/Event/08/03.jpg",
      "/Event/08/04.jpg",
      "/Event/08/05.jpg",
      "/Event/08/06.jpg",
      "/Event/08/07.jpg",
      "/Event/08/08.jpg",
      "/Event/08/09.jpg",
    ],
  },
  {
    id: 9,
    type: "Artist Talk / Lecture",
    date: "2019.8.2",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#21 Lecture ‘Photobook Building’",
    body_en:
      "At FNL #21, we talked about the theme of ‘Making a Book’ which was similar to building a house. We were able to think about photography which shows a moment and a 'book', which weaves the flow of images together. Through well-made books and on unfolded pages, the readers could experience the infinite space. It was a time to think of the medium of \"book\" more broadly by opening a collection of photos in various forms, such as an accordion-style book, a book with folding paper, and a book not in square shape. All of the books introduced at FNL are available in the archive room, D’ark Room. In the exhibition ‘Book of Lights , you can also see the artist's books containing the works on display at D’ark Room. The exhibition will run until the end of September.\n \nFeaturing: Sangyon Joo",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#21 강연 <사진집짓기>",
    body_ko:
      "스물 한 번째 진행된 FNL <사진집짓기>의 모습입니다. ‘책이라는 하나의 공간 안을 구체화시키는 과정은 마치 집을 짓는 것과 같다’라는 주제를 가지고 이야기를 나누었습니다. 사진의 특성인 ‘한 장’ 혹은 ‘한 순간’이 갖는 의미를 유지하면서 그것들의 흐름을 엮는 ‘책’이라는 매체의 의미에 대해 생각할 수 있었습니다. 잘 만들어진 책들을 보며 페이지 안에 펼쳐지는 무한한 공간을 경험할 수 있었습니다. 아코디언 형식으로 펼쳐지는 책이나, 접지를 활용한 방식, 네모난 형태를 벗어난 책 등, 사진의 종류에 따라 다양한 형태로 엮여있는 사진집을 직접 펼쳐보면서 ‘책’이라는 매체를 보다 넓게 생각할 수 있게 된 시간이었습니다. FNL에서 소개해드린 책은 모두 다크룸의 아카이브룸에서 열람하실 수 있습니다. 다크룸에서 진행되고 있는 <빛들의 책> 전시에서는 전시된 작품들이 담긴 아티스트북도 볼 수 있습니다. 전시는 9월 말까지 진행됩니다.\n \n강연자: 주상연",
    images: [
      "/Event/09/01.jpg",
      "/Event/09/02.jpg",
      "/Event/09/03.jpg",
      "/Event/09/04.jpg",
      "/Event/09/05.jpg",
      "/Event/09/06.jpg",
      "/Event/09/07.jpg",
    ],
  },
  {
    id: 10,
    type: "Artist Talk / Lecture",
    date: "2019.7.26",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#20 Lecture ‘Photo-Poetics’",
    body_en:
      "In FNL #20, we had time to consider ‘Photography’ in various ways that we encountered and used every day. We had time to think about photography as a tool of recording and expression, and to relearn photography as a poem by looking at images and the photo books. The exhibition ‘Book of Lights’ at D’ark Room consists of works with photos and poems. The exhibition will run until the end of August.\n \n \nFeaturing: Sangyon Joo",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#20 강연 <사진·시 作>",
    body_ko:
      "7월 26일 다크룸에서 진행된 <사진·시 作>의 모습입니다. 매일 접하고 사용하는 ‘사진’을 다양하게 인식하며 바라볼 수 있는 시간을 가졌습니다. 필요에 의해, 기록을 위해 혹은 표현 수단으로의 사진에 대해 생각해보고, 강연이 끝난 후엔 시처럼 쓰여진 이미지들과 그를 담아낸 사진책들을 보며 ‘시’로서의 사진을 다시 깨닫는 시간을 가졌습니다. 다크룸에서 진행되고 있는 <빛들의 책> 전시는 사진과 시가 함께하는 작품들로 구성되어 있습니다. 전시는 8월 말까지 진행됩니다.\n \n강연자: 주상연\n",
    images: [
      "/Event/10/01.jpg",
      "/Event/10/02.jpg",
      "/Event/10/03.jpg",
      "/Event/10/04.jpg",
      "/Event/10/05.jpg",
      "/Event/10/06.jpg",
    ],
  },
  {
    id: 11,
    type: "Artist Talk / Lecture",
    date: "2019.7.20",
    place_en: "Datz Museum of Art",
    title_en: "The Lumen Project",
    body_en:
      "‘The Lumen Project’ by Amanda Machand, who participated in  Datz Residency, was held in Datz Museum of Art. This project, which started in 2017, was conducted for the third time in Korean. \nParticipants sat on photo paper and meditated, and while sitting, sunlight reacted to the photo paper, leaving a trace. After about 30 minutes of meditation, a large circle was drawn on photo paper to follow the shape of the person sitting, and a large lumen print was created. The lumen print created through this event can be seen as the part of works in the next exhibition ‘Synesthesia : The Space Between’ at Datz Museum of Art.\n \nFeaturing: Amanda Marchand(Artist)",
    place_ko: "닻미술관",
    title_ko: "루멘 프로젝트",
    body_ko:
      "닻 레지던시 참여로 한국에 방문한 아만다 마찬드 작가의 <루멘 프로젝트>가 닻미술관에서 진행되었습니다. 2017년부터 시작된 이 프로젝트는, 이번 한국에서 진행한 것이 세번 째 였습니다. 참여자들은 사진 인화지 위에 앉아 명상을 하고, 앉아 있는 동안 햇빛이 인화지에 반응을 일으켜 흔적을 남기는 방식입니다. 약 30분간의 명상의 시간이 지나면 앉아 있는 사람의 형태를 따라 인화지에 큰 원의 모양이 그려지고, 큰 크기의 루멘 프린트가 만들어집니다. 그리고 작가는 여기에 참여한 사람들 모두의 사인을 담아 참여자들에게 선물로 선물로 줍니다.\n \n작가가 초대한 이 프로젝트는, 우리에게 빠르게 흘러가는 일상 가운데 침묵과 명상의 시간을 갖게 해주고 동시대를 살아가는 사람들에게 공동체의 중요성을 상기시켜 줍니다. 이번 행사를 통해 만들어진 루멘 프린트는 닻미술관의 다음 전시 <다른 감각들의 공간>에서 전시 작품으로 만나보실 수 있습니다.\n \n참여작가: 아만다 마찬드",
    images: ["/Event/11/01.jpg", "/Event/11/02.jpg", "/Event/11/03.jpg"],
  },
  {
    id: 12,
    type: "Artist Talk / Lecture",
    date: "2019.7.19",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#19 Book Talk <Yes, to everything>",
    body_en:
      "‘The Lumen Project’ by Amanda Machand, who participated in  Datz Residency, was held in Datz Museum of Art. This project, which started in 2017, was conducted for the third time in Korean. \nParticipants sat on photo paper and meditated, and while sitting, sunlight reacted to the photo paper, leaving a trace. After about 30 minutes of meditation, a large circle was drawn on photo paper to follow the shape of the person sitting, and a large lumen print was created. The lumen print created through this event can be seen as the part of works in the next exhibition ‘Synesthesia : The Space Between’ at Datz Museum of Art.\n \nFeaturing: Amanda Marchand(Artist)",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#19 북토크 <Yes, to everything>",
    body_ko:
      "7월 19일 다크룸에서 진행한 아만드 마찬드 작가의 북토크 모습입니다. 이번 FNL의 제목인 <Yes, to everything>처럼 작가가 모든 것을 대하는 긍정적인 태도에 대한 이야기와 닻프레스에서 소개된 책 「Night Garden」을 비롯한 작가의 작업과 책에 대한 전반적인 이야기를 들을 수 있었습니다. 특히 작가가 손으로 직접 만든 더미북들을 보며 출판물로 진행되기까지의 과정과 작가의 작품세계를 더욱 깊이 이해할 기회가 되었습니다. 곧 출간 예정인 아만다 마찬드 작가의 「Nothing Will Ever be the Same Again」도 기대해 주시길 바랍니다.\n \n참여작가: 아만다 마찬드",
    images: [
      "/Event/12/01.jpg",
      "/Event/12/02.jpg",
      "/Event/12/03.jpg",
      "/Event/12/04.jpg",
      "/Event/12/05.jpg",
      "/Event/12/06.jpg",
      "/Event/12/07.jpg",
      "/Event/12/08.jpg",
    ],
  },
  {
    id: 13,
    type: "Artist Talk / Lecture",
    date: "2019.6.7",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#18 Book Talk: ‘Pneuma’",
    body_en:
      "Book talk was held as a celebration event for the publication ‘Pneuma’ by Il-am Jang. With photographs and video works containing the shape of rock and the flow and sound of water, we had time to listen to the story of Yoseonam, which Jang had been looking for a long time. In order to better understand the book, the artist talked about the process of selecting among the numerous photographs taken over 18 years and making the structural flow of the book. The book can be purchased at D’ark Room and the online store of Datz Press.\n \nFeaturing: Ilam Jang(Artist)",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#18 북토크: 「프뉴마」",
    body_ko:
      "장일암 작가의 「프뉴마Pneuma」 책 출간을 기념하여 북토크가 진행되었습니다. 바위의 모습, 물의 흐름과 소리가 담긴 사진과 영상 작업들로 작가님이 오랜시간 바라봐 온 요선암에 대한 이야기를 들을 수 있었습니다. 대상을 바라보고, 사진으로 전달하는 과정에 대한 이야기를 시적으로 엮은 「프뉴마」를 깊이 이해할 수 있는 시간이었습니다. 18년이 넘는 시간 동안 촬영한 수많은 사진 중 책에 들어가게 된 50장의 이미지 선정에 대한 과정과 책의 구조적인 흐름에 대한 이야기도 책을 이해하는 데 깊은 도움을 주었습니다. 책은 오프라인 서점인 다크룸과 닻프레스의 온라인 스토어에서 만날 수 있습니다.\n \n참여작가: 장일암",
    images: [
      "/Event/13/01.jpg",
      "/Event/13/02.jpg",
      "/Event/13/03.jpg",
      "/Event/13/04.jpg",
      "/Event/13/05.jpg",
    ],
  },
  {
    id: 14,
    type: "Book Fair",
    date: "2019.4.12 - 2019.4.14 ",
    place_en: "Printed Matter, The Geffen Contemporary at MOCA",
    title_en: "LA ART BOOK FAIR 2019",
    body_en:
      "LA Art Book Fair is a book fair specializing in art books hosted by Printed Matter, Inc. Printed Matter is a non-profit organization founded in 1976 and has had a great influence on the dissemination of art books and the development of the independent publishing market. Currently, it operates an independent bookstore specializing in artbooks located in New York and hosts the book art fair twice a year: New York Art Book Fair and LA Art Book Fair twice a year.\nOver 390 artists, collectors, publishers, and organizations from all over the world participated at the fair. This was Datz’s second participation and we were included in the section of ‘Focus:Photography’ in which the gathered publishers focused on photography. \nBy meeting people who loved artbooks in person and seeing how people are moved by books, we confirmed our efforts. It was a meaningful time to meet people who willingly own great artist books and to get strength from their warm cheerful words and the appearance to move forward.",
    place_ko: "Printed Matter, The Geffen Contemporary at MOCA",
    title_ko: "LA 아트북 페어 2019 ",
    body_ko:
      "LA 아트북페어는 Printed Matter,Inc 에서 주최하는 아트북 전문 북페어입니다. Printed Matter는 1976년에 처음 설립된 비영리단체로, 지금까지 아트북의 보급과 독립출판 시장의 발전에 큰 영향을 주고 있습니다. 현재 뉴욕에 위치한 아트북 전문 독립서점을 운영하면서 1년에 2회, 뉴욕 아트북 페어와 LA 아트북 페어를 주최하고 있습니다.\n \n이번 페어에는 세계 각지에서 390여 명의 아티스트, 콜렉터, 출판사, 기관들이 참여했습니다. 닻프레스는 이번이 두번째 참여로, 사진을 중점적으로 다루는 출판사들이 모여있는 Focus: Photography 섹션에 속하게 되었습니다. \n직접 사람들을 만나 책과 작업에 대한 이야기를 나누고, 책을 통해 감동을 받는 모습을 보는 것은 그동안 책을 만들기 위해 고민한 노력의 확인이자, 또 앞으로 나아갈 힘을 얻는 계기인 것 같습니다. 뜻깊은 인연으로 주인을 만나게 된 책들, 따뜻한 응원의 말들, 책을 통해 진심으로 소통하고 감동받던 사람들을 통해 많이 배울 수 있던 감사한 시간이었습니다.",
    images: [
      "/Event/14/01.jpg",
      "/Event/14/02.jpg",
      "/Event/14/03.jpg",
      "/Event/14/04.jpg",
      "/Event/14/05.jpg",
      "/Event/14/06.jpg",
    ],
  },
  {
    id: 15,
    type: "Book Fair",
    date: "2019.2.2 - 2019.2.6",
    place_en: "Craneway Pavilion & San Francisco Art Institute Graduate Center",
    title_en: "CODEX 2019 & Lecture at Photo Alliance ",
    body_en:
      "In 2019, Datz Press's first official event was the Codex Book fair, which had been held for three days and recently has been held for four days. Codex Book Fair is the world's three largest artbook fairs held every two years in San Francisco. Book artists, artists, collectors and interested people from all over the world gather to share their publications and ideas with each other for four days in The Craneway Pavilion. \nXianlu Yi's art book 'Grass', which reconstructed Kim Su-yong's poem 'Grass', was also introduced for the first time in the Codex book fair. It is the most liked and most described book in the book fair. Prior to the book fair, CEO of Datz Press, Sangyon Joo, attended the annual event of the nonprofit photo organization, Photo Alliance, and gave a presentation on the theme of 'Exhibits and Books'. We thank Linda Connor, Lonnie Graham, Minny Lee, Mary Daniel Hobson, Peter P. Blank, Anne Veh, Amanda Marchand and Hendrik Paul for their support.\n",
    place_ko: "Craneway Pavilion & San Francisco Art Institute Graduate Center",
    title_ko: "CODEX 2019 & 포토 얼라이언스 강연",
    body_ko:
      "2019년 첫 공식 행사로 CODEX 북페어를 풍성히 마쳤습니다.​ 코덱 북페어는 샌프란시스코에서 2년마다 열리는 세계 3대 아트북 페어입니다. 전세계의 북 아티스트, 예술가, 수집가 및 관심있는 모두가 모여 서로의 출판물과 아이디어를 공유하는 자리로써, 높아지는 관심을 반영하듯 이번 회부터 3일간 열리던 북페어가 4일 동안 크래인웨이 파빌리온The Craneway Pavilion에서 진행되고 있습니다. 올해도 많은 관심 가운데 닻프레스가 마음을 담아 제작한 출판물들을 소개했으며 그 중 김수영 시인의 시 ‘풀’을 재구성한 이현노 디자이너의 아트북 '풀'은 큰 관심을 받았습니다. 코덱 북페어에서 가장 많은 분들이 좋아해 주시고 또 가장 많이 설명한 책입니다.\n \n코덱 북페어에 앞서 미국 서부 사진계의 허브 역할을 하는 비영리 사진 조직 포토 얼라이언스Photo Alliance의 연례행사에 참가하여 닻프레스의 주상연 대표가 ‘전시와 책’이라는 주제로 강연을 진행했습니다. 먼길까지 찾아와주신 모든 분들과 도움 주시고 응원해 주신 닻프레스의 작가들, 린다 코너Linda connor, 로니 그래험Lonnie Graham, 미니 리Minny Lee, 메리 다니엘 홉슨Mary Dary Hobson, 피터 블랭크Peter P. Blank, 아만다 마찬드Amanda Marchand, 헨드릭 폴Hendrik Paul, 큐레이터 앤 베이Anne Veh께 진심으로 감사의 말씀드립니다.\n",
    images: [
      "/Event/15/01.jpg",
      "/Event/15/02.jpg",
      "/Event/15/03.jpg",
      "/Event/15/04.jpg",
      "/Event/15/05.jpg",
      "/Event/15/06.jpg",
    ],
  },
  {
    id: 16,
    type: "Exhibition",
    date: "2018.11.21 - 2019.1.29",
    place_en: "Kyungpook National University Art museum",
    title_en: "Writing Art, Drawing Books",
    body_en:
      "At kyungpook National University Art museum in Daegu, Datz Press participated in the exhibition.\nThis exhibition begins with a discussion of the fragmentation of the content and form of the book and the role of the book today. This exhibition started by thinking about a book, a comprehensive art made up of text and images, instead of simply conveying knowledge, experience, and values.\n \nThrough the exhibition, it was reinterpreted and presented the meaning of the book as a work of art by focusing on the 'method' of accepting the book, not the book as a dictionary meaning. Datz Press received a good response by introducing Datz's publications to showcase the possibilities of books that can be understood through the interaction of various senses. In addition to the inherent functionality of the book, which was handcrafted in the workshop of Datz Press, the artist book that exists as an independent work of the artist was exhibited to introduce the book as a medium of visual art.",
    place_ko: "경북대학교 미술관",
    title_ko: "예술을 쓰다, 책을 그리다",
    body_ko:
      "대구에 위치한 경북대학교의 미술관에서 책에 대해 고찰하는 전시 <예술을 쓰다, 책을 그리다>에 닻프레스의 출판물과 아카이브 자료로 참여하였습니다. 이 전시는 책의 내용과 형태가 해체되는 현상과 오늘날 책의 역할에 대한 논의에서 시작하여, 단순히 지식과 경험, 가치를 전달하는 매개체에서 벗어나 텍스트와 이미지로 이루어진 하나의 종합예술인 책에 대해 고심하며 출발하였습니다. 또한 사전적 의미로서의 책이 아니라 책을 수용하는 ‘방식’에 주목하여 예술작품으로서의 책의 의미를 재해석하고 제시하려 합니다.\n \n닻프레스는 전시를 통해 여러 감각들의 상호작용을 통해 이해하게 되는 책의 가능성을 선보이고자 닻의 출판물을 소개하여 좋은 반응을 얻었습니다. 또한 닻프레스의 공방에서 수공으로 제작한, 책이 가진 고유의 기능성을 넘어 예술가의 독립된 작품으로서 존재하는 아티스트북을 전시하여 시각예술의 매체로서의 책을 소개하였습니다. ",
    images: ["/Event/16/01.jpg", "/Event/16/02.jpg", "/Event/16/03.jpg"],
  },
  {
    id: 17,
    type: "Artist Talk / Lecture",
    date: "2018.11.3",
    place_en: "Datz Museum of Art",
    title_en: "Round Talk: Exhibition ‘Journey of Transformation’",
    body_en: "",
    place_ko: "닻미술관 라운지",
    title_ko: "전시연계 라운드 토크: <변화의 여정>",
    body_ko:
      "<변화의 여정Journey of Transformation> 전시 참여작가 브라이언 오스틴, 메리 다니엘 홉슨, 미니 리와 협력 큐레이터인 앤 베이가 함께한 라운드 토크입니다. 변화의 여정은 각각 고유하게 하나로 연결됩니다. 보이지 않는 세포의 한 부분이었던 존재가 미시의 여정을 통해 한 인간으로 삶을 이루다 우주 속의 먼지로 돌아갑니다. 생기가 머무르는 동안 밝은 눈으로 세상을 보고 깊이 성찰하는 여행자와도 같은 그들과 함께 경계를 넘어 흐르는 시공간의 여정에 대한 이야기를 나누는 시간이었습니다. 작가들의 작업은 서로 공명하며 관객과 조우합니다. 작가들과 함께 전시를 관람한 여운을 지낸 채, 관람객과 참여작가, 협력 큐레이터, 기획자, 스텝과 함께 매우 친밀하고 밀도 높은 토크를 나누었습니다. \n \n참여작가: 브라이언 오스틴, 메리 다니엘 홉슨, 미니리, 앤 베이(협력 큐레이터)",
    images: [
      "/Event/17/01.jpg",
      "/Event/17/02.jpg",
      "/Event/17/03.jpg",
      "/Event/17/04.jpg",
      "/Event/17/05.jpg",
    ],
  },
  {
    id: 18,
    type: "Artist Talk / Lecture",
    date: "2018.11.2",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#17 Book Talk: ‘Million Years’",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#17 북토크: 「Million Years」",
    body_ko:
      "11월 2일 진행한 미니 리 작가의 「Million Years」 북토크 모습입니다. 작가가 사진을 시작하게 된 계기부터, 작가로서의 여정, 책을 만들게 된 과정과 책에 담긴 이미지와 시에 대한 친절한 설명 모두 차근차근 들을 수 있어서 흥미로운 시간이었습니다. 사진작가이자 북아티스트로서, 자신의 작업을 책이라는 형태를 통해 어떻게 정리하고 발전시켜 나가는지 볼 수 있었습니다. 독립출판의 과정뿐만 아니라 출판사와의 협업을 통해 작품집을 만드는 과정도 함께 들을 수 있었습니다. 미니리 작가의 작품집은 다크룸에서 직접 보실 수 있습니다. 미니 리 작가의 작품을 비롯해 매거진 깃에 참여한 작가들의 선정된 작품들이 다크룸에서 전시되고 있습니다.\n \n참여작가: 미니 리",
    images: [
      "/Event/18/01.jpg",
      "/Event/18/02.jpg",
      "/Event/18/03.jpg",
      "/Event/18/04.jpg",
      "/Event/18/05.jpg",
      "/Event/18/06.jpg",
      "/Event/18/07.jpg",
      "/Event/18/08.jpg",
      "/Event/18/09.jpg",
    ],
  },
  {
    id: 19,
    type: "Artist Talk / Lecture",
    date: "2018.10.26",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#16 Book Talk: Gitz vol.10 ‘Process and Attitude’",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#16 북토크: 깃10호 「과정과 태도」",
    body_ko:
      "매거진 깃 10호 「과정과 태도」와 닻미술관에서 열린 <변화의 여정> 전시를 위해 참여작가 메리 다니엘 홉슨, 브라이언 오스틴, 공동 큐레이터 앤 베이가 한국에 방문하였습니다. 전시 오픈 전날 다크룸에서는 작가들을 초대해 매거진 깃과 관련하여 북토크 행사를 가졌습니다. 매거진 깃에 실린 작가들의 작업에 대한 전반적인 이야기와 인터뷰에는 실리지 않은 비하인드 이야기까지 들을 수 있던 시간이었습니다.\n \n각자의 삶에서 일어나는 일들에 집중하여 내면의 소리를 듣고, 삶의 여정 가운데 그들만의 특별한 방법으로 작업하는 작가들의 태도는 잔잔한 울림을 주었습니다. 자세한 내용은 매거진 깃10호에서 확인할 수 있습니다.\n \n참여작가: 메리 다니엘 홉슨, 브라이언 오스틴, 앤 베이(협력 큐레이터), 주상연(발행인)",
    images: [
      "/Event/19/01.jpg",
      "/Event/19/02.jpg",
      "/Event/19/03.jpg",
      "/Event/19/04.jpg",
      "/Event/19/05.jpg",
      "/Event/19/06.jpg",
      "/Event/19/07.jpg",
      "/Event/19/08.jpg",
      "/Event/19/09.jpg",
      "/Event/19/10.jpg",
      "/Event/19/11.jpg",
      "/Event/19/12.jpg",
      "/Event/19/13.jpg",
      "/Event/19/14.jpg",
      "/Event/19/15.jpg",
    ],
  },
  {
    id: 20,
    type: "Artist Talk / Lecture",
    date: "2018.9.14",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#15 Artist Talk: Seongyeon Jo",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#15 아티스트 토크: 조성연",
    body_ko:
      "지난 금요일, 사진가 조성연 작가의 새로운 사진집 「지고 맺다Arranging Life」의 출판 기념전과 함께 아티스트 토크가 진행되었습니다. 이전의 작업들에서부터 새롭게 선보인 ‘지고맺다Arranging Life’ 시리즈까지, 조성연 작가님의 시선과 생각의 흐름을 들을 수 있었던 시간이었습니다. 최근 도시 농부로서 삶의 시작한 작가는 삶과 작업이 일치되는 과정 가운데 있습니다. 책을 통해 보여지는 시리즈인 식물이 피고 지고 맺기까지의 흔적들이 배어있는 사진들에 관한 자세한 설명과 해석을 들을 수 있었습니다. 이번 아티스트 토크에서는 작가님이 직접 준비하신 케이터링 덕에 음식을 함께 즐기며 이야기를 나눌 수 있었습니다.\n조성연 작가의 ‘지고 맺다 Arranging Life’는 약 한 달간 다크룸에서 전시됩니다.\n \n참여작가: 조성연",
    images: [
      "/Event/20/01.jpg",
      "/Event/20/02.jpg",
      "/Event/20/03.jpg",
      "/Event/20/04.jpg",
      "/Event/20/05.jpg",
      "/Event/20/06.jpg",
      "/Event/20/07.jpg",
      "/Event/20/08.jpg",
      "/Event/20/09.jpg",
    ],
  },
  {
    id: 21,
    type: "Artist Talk / Lecture",
    date: "2018.7.27",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#14 Book Talk ‘Deer Book, From Tree’",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#14 북토크 <Dear Book, From Tree> ",
    body_ko:
      "지난 금요일 저녁, 흥미로웠던 북토크의 모습입니다. 책과 사진이 지닌 특성과 개념부터 펼쳐보지 않으면 놓치기 쉬운 보물같은 24권의 사진책에 대한 친절한 설명을 들을 수 있었습니다. 과거부터 현재까지 자연을 담아온 사진가들의 시선과 그들의 작업이 책으로 담긴 다양한 이야기까지 들을 수 있는 알찬 시간이었습니다.\n \n강연자: 주상연",
    images: [
      "/Event/21/01.jpg",
      "/Event/21/02.jpg",
      "/Event/21/03.jpg",
      "/Event/21/04.jpg",
      "/Event/21/05.jpg",
      "/Event/21/06.jpg",
    ],
  },
  {
    id: 22,
    type: "Artist Talk / Lecture",
    date: "2018.7.13",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#13 Artist Talk: Mikyung Kim",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#13 아티스트 토크: 김미경",
    body_ko:
      "화가 김미경 작가의 아티스트 토크가 있었던 7월 13일 저녁의 모습입니다. 작가는 개인의 정서를 평면의 기하학 형태로 쌓아나가는 회화작업을 해오고 있습니다. 오늘은 특별히 이번에 출간된 책 「나무에게Tree Though」에서 선보인 작품 세계에 대해 설명하는 시간을 가졌습니다. 작가가 흑백 필름에 담았던 나무들을 17년 뒤에 암실에서 인화지에 다시 새기고, 각각의 나무에 이름을 지어준 이야기를 들을 수 있었습니다. 작가의 잔잔한 목소리가 나무들의 이미지와 잘 어우러 졌습니다. 책에 실린 18점의 오리지널 젤라틴 실버프린트는 다크룸에서 이번 달 말까지 전시됩니다.\n \n참여작가: 김미경\n",
    images: [
      "/Event/22/01.jpg",
      "/Event/22/02.jpg",
      "/Event/22/03.jpg",
      "/Event/22/04.jpg",
      "/Event/22/05.jpg",
      "/Event/22/06.jpg",
      "/Event/22/07.jpg",
      "/Event/22/08.jpg",
      "/Event/22/09.jpg",
      "/Event/22/10.jpg",
    ],
  },
  {
    id: 23,
    type: "Artist Talk / Lecture",
    date: "2018.5.26",
    place_en: "Datz Museum of Art",
    title_en: "Artist Talk: Exhibition ‘The Artist’s Garden’",
    body_en: "",
    place_ko: "닻미술관 기획전시실 및 라운지",
    title_ko: "전시연계 아티스트 토크: <예술가의 정원>",
    body_ko:
      "<예술가의 정원The Artist’s Garden> 전시에 참여한 4인의 작가 중 이해인, 조성연, 허구영 3명의 작가와 함께 아티스트 토크 시간을 가졌습니다. ‘예술가에게 정원이란 어떤 의미인가’라는 질문에서 시작한 전시의 의미를 되새기며, 작가들에게 정원이 어떻게 영감을 주었는지 관객과 대화를 나누었습니다. \n \n이해인은 2008년부터 2010년까지 이어온 ‘Memory’ 작업에서 뉴타운 개발로 사라진 집과 가족들, 이웃에 관한 기억들을 끄집어내고 다시 그림으로 재조합하는 과정을 담았습니다. 조성연은 발아된 싹을 보며, 씨앗은 생명이 다한 흔적이 아니라 새로운 시작을 지닌 무한한 에너지의 응축이라는 생각을 했다고 합니다. 아무런 움직임 없이 숨도 쉬지 않을 것 같던 씨앗들은, 빛, 공기, 물만으로 세상과의 만남을 준비 중이었음 깨달으며, 작가는 그 씨앗들은 생명력을 품은 작은 우주라고 말하고 있습니다. 작가는 예술은 삶의 경작임을 몸소 실천하며 그 과정을 기록합니다. 허구영은 이번 전시에서 선보인 ‘낭만정원’ 시리즈를 제작하며, 낭만적인 정원에서 낭만적 그림을 그리는 시대 착오적인 실행을 했다고 합니다. 주체의 시대성에 거스르고 역행하는 행위를 통해 주체의 균열과 이반의 쾌감을 맛보았다고 유쾌하게 말합니다. 오랜시간 다채롭게 예술가의 뮤즈가 되어온 정원에서 내밀하고 아름다운 이야기를 나눈 시간이었습니다. \n \n참여작가: 이해인, 조성연, 허구영",
    images: ["/Event/23/01.jpg"],
  },
  {
    id: 24,
    type: "Artist Talk / Lecture",
    date: "2018.4.6",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#12 Book Talk: ‘Silent Prayer’",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#12 북토크: 「묵안 默安」 ",
    body_ko:
      "김정인 작가의 사진집 「묵안Silent Prayer」의 출간을 기념하여 전시가 열리고, 오픈 첫날 북토크가 진행되었습니다. 작업 ‘묵안’의 시작부터 제목이 만들어진 과정, 그리고 책이 만들어지기까지의 과정을 차근차근히 듣는 시간을 가졌습니다. 책이 만들어지는 과정이 담긴 사진과 영상를 보며 작가의 설명이 더해져 책으로 구현되는 사진언어를 깊이 이해할 수 있는 시간이었습니다. 책이 세상에 나온지 이틀만이었던 행사 당일에 1st 에디션이 완판되는 기쁜 소식도 있었습니다. 북토크에 자리해주신 많은 분들께 감사함을 전합니다.\n \n참여작가: 김정인\n",
    images: [
      "/Event/24/01.jpg",
      "/Event/24/02.jpg",
      "/Event/24/03.jpg",
      "/Event/24/04.jpg",
      "/Event/24/05.jpg",
      "/Event/24/06.jpg",
      "/Event/24/07.jpg",
      "/Event/24/08.jpg",
      "/Event/24/09.jpg",
      "/Event/24/10.jpg",
    ],
  },
  {
    id: 25,
    type: "Artist Talk / Lecture",
    date: "2018.2.23",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#11 Book Talk: ‘Art is already in you mind’",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#11 북토크: 「예술은 이미 당신의 마음속에 있다」",
    body_ko:
      "우순옥 작가의 새로운 작품집 '예술은 이미 당신의 마음속에 있다' 북토크가 진행된 2월 23일 저녁의 모습입니다. 책을 함께 보며 삶이 예술이자 예술이 삶이 되는 우순옥 작가의 태도에 대한 생각을 들으며 작업 하나 하나에 대한 친절한 설명과 뒷이야기, 에피소드 등을 들을 수 있는 시간이었습니다. 이번 책은 작가의 초기 작품부터 지금까지의 작업까지 모두 담긴 작품집인 만큼, 작가의 작품세계를 넓고 깊게 들을 수 있는 시간이었습니다. 책이 만들어지기까지의 디자인과 제작 과정을 닻프레스의 디자이너를 통해 듣고 북사이닝 시간도 함께 가졌습니다. \n \n참여작가: 우순옥\n",
    images: [
      "/Event/25/01.jpg",
      "/Event/25/02.jpg",
      "/Event/25/03.jpg",
      "/Event/25/04.jpg",
      "/Event/25/05.jpg",
      "/Event/25/06.jpg",
      "/Event/25/07.jpg",
    ],
  },
  {
    id: 26,
    type: "Artist Talk / Lecture",
    date: "2018.1.19",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#10 Artist Talk: Hye-Ryoung Min",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#10 아티스트 토크: 민혜령",
    body_ko:
      "닻프레스의 2018년 첫 기획출판물인 「기억의 재구성Re-membrance of the Remembrance」의 출간일이자, 출판기념전의 첫 날, 민혜령 작가의 아티스트 토크가 진행되었습니다. 작가의 초기작업부터 최근 작업까지 순차적으로 볼 수 있는 좋은 기회였습니다. 어릴 적부터 기록에 대한 남다른 애정으로 많은 일기장을 남기고, 그 일기장을 다시 기록하고 사진으로 재구성하는 작업을 통해 자신의 이야기를 만들어가는 과정을 들을 수 있었습니다. 이번 토크를 통해 지극히 개인적이지만 모두가 공감할 수 있는 지점들을 보다 깊이 이해할 수 있었습니다. 또한 ‘기억의 재구성’의 책 제작을 담당한 닻프레스 디렉터의 목소리를 통해 컨셉을 정하는 기획 단계부터 디자인과 제작 과정에 대한 이야기를 듣는 시간과, 작가의 북사이닝 시간도 가졌습니다.\n \n참여작가: 민혜령",
    images: [
      "/Event/26/01.jpg",
      "/Event/26/02.jpg",
      "/Event/26/03.jpg",
      "/Event/26/04.jpg",
      "/Event/26/05.jpg",
      "/Event/26/06.jpg",
      "/Event/26/07.jpg",
      "/Event/26/08.jpg",
    ],
  },
  {
    id: 27,
    type: "Artist Talk / Lecture",
    date: "2017.9.15",
    place_en: "Datz Museum of Art",
    title_en: "Round Talk: Exhibition ‘Resonant Voices’",
    body_en: "",
    place_ko: "닻미술관 라운지",
    title_ko: "전시연계 라운드 토크: <공명의 소리>",
    body_ko:
      "<공명의 소리Resonant Voices>전시와 연계한 라운드 토크는 전시의 참여작가의  의미 깊은 프로젝트의 화합에 대해 다루었습니다. 미국에서 초청한 두 명의 사진가, 로니 그래험과 제인 볼드윈은 각각 ‘세계와의 대화A Conversation with the World’, ‘남겨진 강: 카라 여인의 이야기Only the River Remains: Kara Women Speak’ 다큐멘터리 프로젝트를 선보이며 타인에 대한 진정 어린 이해와 관용, 사랑의 가치에 대해 깊이 있는 대화를 건넵니다. 로니 그래험이 촬영한 27명의 인물 사진이 관람객을 둘러싸고 카라 여인과 오모강의 풍경이 이들과 함께 호흡하며 마주하는 전시공간의 울림을 감상하며 나누는 장입니다. 그들의 프로젝트는 결국 같은 이야기를 향합니다. 바로 각자 삶의 문화를 지켜내기 위해 고군분투하는 모습은 우리의 삶과 결코 다르지 않다는 사실입니다. 이는 타인의 목소리에 진심으로 귀 기울여야 하는 이유이기도 합니다. \n \n작가와 관객이 나누는 토크는 타인의 삶에 대한 공감으로 공명합니다. 토크에 이어, 로니 그래험은 참여자들에게 특별한 선물을 하였습니다. 자신의 오래된 폴라로이드 필름 카메라로 참여자들의 자화상을 촬영해주었습니다. 실제 전시에 기반한 작업방식을 그대로 재현해 더욱 의미있는 시간이었습니다. \n \n참여작가: 로니 그래험, 제인 볼드윈, 앤 베이(협력 큐레이터)",
    images: [
      "/Event/27/01.jpg",
      "/Event/27/02.jpg",
      "/Event/27/03.jpg",
      "/Event/27/04.jpg",
      "/Event/27/05.jpg",
      "/Event/27/06.jpg",
      "/Event/27/07.jpg",
    ],
  },
  {
    id: 28,
    type: "Artist Talk / Lecture",
    date: "2017.9.8",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#9 Artist Talk: Jane Baldwin, Lonnie Graham",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#9 아티스트 토크: 제인 볼드윈, 로니 그래험",
    body_ko:
      "두 달 만에 열린 아홉번째 FNL이 지난 9월 8일에 진행되었습니다. 현재 닻미술관에서 진행중인 <공명의 소리Resonant Voices>의 작가 두명, 제인 볼드윈과 로니 그래험 모두 첫 한국 방문으로 9월 9일에 닻미술관에서 열린 전시 오프닝에 앞서 다크룸에서 아티스트 토크를 가졌습니다. 이번 전시 <공명의 소리>의 협력 큐레이터인 앤 베이의 소갯말로 시작으로 제인 볼드윈의 잔잔하면서도 호소력이 짙은 목소리를 통한 그녀의 이야기와 로니 그래험의 유쾌하면서도 깊은 단단함이 있는 토크가 진행된 뜻 깊은 시간이었습니다.\n \n참여작가: 제인 볼드윈, 로니 그래험, 앤 베이(협력 큐레이터)",
    images: [
      "/Event/28/01.jpg",
      "/Event/28/02.jpg",
      "/Event/28/03.jpg",
      "/Event/28/04.jpg",
      "/Event/28/05.jpg",
      "/Event/28/06.jpg",
      "/Event/28/07.jpg",
      "/Event/28/08.jpg",
      "/Event/28/09.jpg",
      "/Event/28/10.jpg",
    ],
  },
  {
    id: 29,
    type: "Artist Talk / Lecture",
    date: "2017.7.14",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#8 Artist Talk: Andrew Gold",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#8 아티스트 토크: 앤드류 골드",
    body_ko:
      "현재 닻미술관에서 진행중인 <물오르다, 물만나다, 물들다water in between>의 참여작가로 한국에 처음 방문한 앤드류 골드가 7월 15일에 열린 전시 오프닝에 앞서 다크룸에서 아티스트 토크를 가졌습니다. 사진작가가 된 배경, 바다와 파도의 사진을 찍고 컬러 암실에서 프린트를 하는 과정, 파도의 형성 과정, 모양과 형태에 관한 과학적인 설명까지 그의 작가로서의 태도와 여정을 흥미롭게 들을 수 있는 시간이었습니다. 진지하고 진솔한 그의 작가적 태도가 관중들에게 좋은 영감을 주었습니다.  \n \n참여작가: 앤드류 골드\n",
    images: [
      "/Event/29/01.jpg",
      "/Event/29/02.jpg",
      "/Event/29/03.jpg",
      "/Event/29/04.jpg",
      "/Event/29/05.jpg",
      "/Event/29/06.jpg",
    ],
  },
  {
    id: 30,
    type: "Artist Talk / Lecture",
    date: "2017.7.7-2017.7.8",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#7 Artist Talk, Critic Class: Linda Connor",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#7 아티스트 토크, 크리틱 클래스: 린다 코너",
    body_ko:
      "지난 7월 7일의 린다코너의 아티스트 토크 모습입니다. 린다코너의 신비로운 작업들과 그녀의 진지하고도 유쾌한 이야기들에 빠져들었던 시간이었습니다. 토크가 끝난 뒤에는 이런저런 질문과 답변이 오갔고 다크룸이 소장하고 있는 린다코너의 여러가지 종류의 프린트와 출판물들을 직접 볼 수 있는 시간도 진행되었습니다. \n \n또한 7월 8일에는 학교를 준비하는 학생들과 작품세계가 깊어지고 있는 작가들이 리뷰이로 참여하여 린다코너와 크리틱 클래스를 가졌습니다. 린다 코너는 한명 한명 작업을 진지하게 대하고 다각도로 바라본 뒤 새로운 시선을 제시하였고 오랜 시간 학교에서 학생들을 가르치고 있는 린다코너의 연륜을 체감할 수 있는 시간이었습니다.\n \n참여작가: 린다 코너\n",
    images: [
      "/Event/30/01.jpg",
      "/Event/30/02.jpg",
      "/Event/30/03.jpg",
      "/Event/30/04.jpg",
      "/Event/30/05.jpg",
      "/Event/30/06.jpg",
      "/Event/30/07.jpg",
      "/Event/30/08.jpg",
      "/Event/30/09.jpg",
      "/Event/30/10.jpg",
    ],
  },
  {
    id: 31,
    type: "Artist Talk / Lecture",
    date: "2017.6.30",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#6 Photo Book Talk: Barbara Bosworth’s Photo Book",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#6 포토북토크: 바바라 보스워스",
    body_ko:
      "닻미술관에서 열리는 <하늘, 바람, 별 그리고 詩> 전시를 기념해 바바라 보스워스가 한국에 두번째 방문을 하였습니다. 닻프레스가 애정하는 작가, 바바라 보스워스의 두번 째 FNL은 그녀의 작품집 「The Meadow」, 「Natural Histories」, 「Behold」를 중심으로 한 북토크였습니다. 눈물과 웃음이 함께한 그녀의 북토크를 통해 책과 작품의 비하인드 스토리들을 깊이 나누며 그녀의 아름다운 영혼을 더 자세히 들여다 볼수 있는 좋은 시간이었습니다. 작가의 작품에 대해 깊이 알게 될 수록 삶과 예술이 하나된 진정한 아티스트의 모습을 엿볼 수 있었습니다.\n \n참여작가: 바바라 보스워스\n",
    images: [
      "/Event/31/01.jpg",
      "/Event/31/02.jpg",
      "/Event/31/03.jpg",
      "/Event/31/04.jpg",
      "/Event/31/05.jpg",
      "/Event/31/06.jpg",
      "/Event/31/07.jpg",
      "/Event/31/08.jpg",
      "/Event/31/09.jpg",
      "/Event/31/10.jpg",
    ],
  },
  {
    id: 32,
    type: "Book Fair",
    date: "2017.2.3 - 2017.2.8",
    place_en: "Craneway Pavilion & San Francisco Art Institute Graduate Center",
    title_en: "CODEX 2017 & Lecture at Photo Alliance ",
    body_en:
      "In the first week of February, Datz Press went to the United States to participate in artist meetings for exhibitions and publications, book fairs and symposiums. Photo Alliance Photo Alliance, a not-for-profit photography organization, serves as a hub for the western world of photography and hosts the book symposium. As the speaker there, the CEO of the Datz Press was invited to introduce ourselves to the public. The CODEX Book Fair, the sixth most celebrated art book fair in the western United States since its first event in 2007, was held this year in Richmond, a port city across from San Francisco. On the first day of the CODEX Book Fair, the photographers Jane Baldwin, Lonnie Graham and the curator Anne Veh joined the meeting for the projects for Magazine Git No. 9, the group shows and publications this year. Through the book fair, Stanford University decided to possess all publications of Datz in its sessions Art & Architecture of the Library. The collection of Datz's publications, along with more than 100 years of books from the prestigious Stanford University Library, is recognized for the unlimited potential of Datz Press, an art book publisher. Four days of communication with artists, photographers, art enthusiasts, and new Datz Press followers were grateful times that gave Datz Press the energy to continue as an art book publisher.",
    place_ko: "Craneway Pavilion & San Francisco Art Institute Graduate Center",
    title_ko: "CODEX 2017 & 포토 얼라이언스 북 심포지움",
    body_ko:
      "닻프레스는 2월 첫째 주, 전시와 출판물 프로젝트를 위한 작가 미팅을 비롯해 여러 이벤트에 참가하기 위해 미국에 다녀왔습니다. 비영리 사진 조직인 포토 얼라이언스Photo Alliance는 미국 서부 사진계에서 허브 역할하며 북 심포지움을 지속적으로 개최하고 있습니다. 그 곳의 강연자로 닻프레스의 주상연 대표가 초대되어 대중에게 닻프레스를 소개하는 시간을 가졌습니다.\n \n2007년 첫 개최 이후 여섯 번째를 맞이하는 아트북 페어인 코덱Codex북 페어는 올해 샌프란시스코와 좁은 바다를 사이에 두고 건너편에 있는 항구도시인 리치먼드에서 열렸습니다. 북 페어의 첫날, 올해 출간될 매거진 깃 9호와 깃 전시, 출판물까지 포함된 프로젝트를 위한 작가 미팅에 사진작가 제인 볼드윈Jane Baldwin, 로니 그래험Lonnie Graham, 큐레이터인 앤 베이Anne Veh 가 함께 했습니다. 심포지엄과 페어를 통해 스탠포드 대학Stanford University은 닻프레스의 전 출판물을 도서관 Art & Architecture의 세션에 소장하기로 결정하였습니다. 미국의 명문 대학인 스탠포드 대학 도서관에 100년 이상 된 책들과 함께 닻 출판물이 소장되는 것은 예술 서적 출판사인 닻프레스의 무한한 가능성을 인정받는다는 의미입니다. 4일간 아티스트, 포토그래퍼, 예술애호가, 그리고 새로운 닻프레스의 팔로워들과의 소통의 시간들은 닻프레스에게 예술 서적 출판사로서 지속할 수 있는 에너지를 주는 감사한 시간들이었습니다. ",
    images: [
      "/Event/32/01.jpg",
      "/Event/32/02.jpg",
      "/Event/32/03.jpg",
      "/Event/32/04.jpg",
      "/Event/32/05.jpg",
      "/Event/32/06.jpg",
      "/Event/32/07.jpg",
      "/Event/32/08.jpg",
      "/Event/32/09.jpg",
      "/Event/32/10.jpg",
    ],
  },
  {
    id: 33,
    type: "Artist Talk / Lecture",
    date: "2016.1.20",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#4 Artist Talk: Gap Chul Lee",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#4 아티스트 토크: 이갑철",
    body_ko:
      "지난 1월 20일 닻프레스 다크룸의 네 번째 FNL 아티스트 토크 및 북 사인회가 있었습니다. 이갑철 작가의 새로운 책 「검은 바람」의 출판 기념으로 열린 이번 행사에는 책에 대한 설명과 함께 작품에 관한 전반적인 내용을 나누었고, 책이 만들어지게 된 과정 또한 깊이있게 들을 수 있는 시간이었습니다. 아티스트 토크 이후 Q&A시간을 통해 작가와 관객들의 심도있는 질문과 대화가 오고 행사 후 직접 작가에게 사인을 받으며 미처 나누지 못한 대화를 나눌 수 있는 시간도 가졌습니다.\n \n참여작가: 이갑철\n",
    images: [
      "/Event/33/01.jpg",
      "/Event/33/02.jpg",
      "/Event/33/03.jpg",
      "/Event/33/04.jpg",
      "/Event/33/05.jpg",
      "/Event/33/06.jpg",
    ],
  },
  {
    id: 34,
    type: "Artist Talk / Lecture",
    date: "2016.9.24",
    place_en: "Datz Museum of Art",
    title_en: "Artist Talk: ‘Artist Book Space’",
    body_en: "",
    place_ko: "닻미술관",
    title_ko: "전시연계 아티스트 토크: <아티스트 북 스페이스>",
    body_ko:
      "<아티스트 북 스페이스>는 ‘책’이라는 공간을 통해 창작의 의미를 구현, 소통, 재해석는 작가들과 닻프레스가 함께한 전시 입니다. 전시 참여작가 중 김윤수, 이창훈 2명의 작가와 함께 아티스트 토크를 진행하였습니다.\n조각/설치미술가 김윤수, 프로젝트/설치미술가 이창훈은 또 다른 시각예술 매체로서의 책이라는 개념을 확장시키거나 이미 제작된 작업을 책 공간 속에 재구성하여 그 창작과정을 다양하게 시각화하는 프로젝트를 선보입니다. 김윤수는 현실 너머의 사색을 통해 관념적인 형상성을 추구해 온 드로잉 작업들을 여러 형식의 책으로 보여주며, 이창훈은 일상 속에서 만나는 대상의 재현을 넘어 형식화한 개념을 단순 반복적인 책 작업으로 재치있게 보여줍니다. \n작가가 닻프레스와 협업하거나 직접 제작한 30여 점의 아티스트 북, 그 제작 과정을 보여주는 더미북, 드로잉과 사진, 출판물 등의 다양한 내용을 관객과 나누는 자리였습니다.\n  \n참여작가: 김윤수, 이창훈",
    images: [
      "/Event/34/01.jpg",
      "/Event/34/02.jpg",
      "/Event/34/03.jpg",
      "/Event/34/04.jpg",
      "/Event/34/05.jpg",
      "/Event/34/06.jpg",
    ],
  },
  {
    id: 35,
    type: "Artist Talk / Lecture",
    date: "2015.12.5",
    place_en: "Datz Museum of Art",
    title_en: "Artist Talk: ‘DARKNESS’",
    body_en: "",
    place_ko: "닻미술관",
    title_ko: "전시연계 아티스트 토크: <DARKNESS>",
    body_ko:
      "<다크니스DARKNESS>는 어두운 침묵의 바다에서 빛을 찾아 홀로 항해하는 돛단배 혹은 섬과 같은 고독한 인간의 실존을 다양하게 은유하고 있는 전시입니다. 이번 전시 참여작가인 이지유, 양희아, 양유연, 김영혜 4명의 작가와 이야기를 나누고 작업에 대한 이야기를 듣는 시간을 가졌습니다. 어둠을 지닌 고독한 빛의 역설을 이야기하고, 절망과 고통 끝에 발아 되는 생의 동력을 향하는 작가들의 에피소드를 듣는 시간이었습니다. 또한, 사회를 통해 결핍된 것, 억압된 의식과 무의식의 욕망을 해소하고 치유하는 예술의 역할을 질문하며, 작가들의 작품이 품어낸 어둠 속에서 빛을 발견하는 역설의 언어에 귀 기울여보는 자리였습니다. 이번 아티스트 토크에서 작가들이 나눈 이야기는 매거진 깃 7호에서도 만나보실 수 있습니다. \n \n참여작가: 이지유, 양희아, 양유연, 김영혜",
    images: [
      "/Event/35/01.jpg",
      "/Event/35/02.jpg",
      "/Event/35/03.jpg",
      "/Event/35/04.jpg",
      "/Event/35/05.jpg",
      "/Event/35/06.jpg",
      "/Event/35/07.jpg",
      "/Event/35/08.jpg",
      "/Event/35/09.jpg",
      "/Event/35/10.jpg",
    ],
  },
  {
    id: 36,
    type: "Artist Talk / Lecture",
    date: "2015.10.24",
    place_en: "Datz Museum of Art",
    title_en: "Book Talk: ‘Island, Jeju’",
    body_en: "",
    place_ko: "닻미술관",
    title_ko: "전시연계 북토크: 「Island, Jeju」",
    body_ko:
      "웨인 레빈은 1945년 로스엔젤레스에서 태어나 30년동안 하와이의 섬 코나에서 수중사진을 찍어왔습니다. 타고난 운동신경으로 해양스포츠를 즐겨온 그는 물 속에서 숨을 참으며 위험하지만 아름다운 사진들을 만들어냅니다. \n순간을 담는 스냅사진의 전통적 기법을 누구보다 잘 보여주고 있으며 생동감있는 그의 사진 속 물은 마치 하늘과도 같고 초현실적인 영감과 생명의 신비로 가득합니다. 또한 최근에는 안개자욱한 산과 하늘을 나는 새를 촬영하여 하늘과 물 속 모든 생물들이 하나되어 조화롭게 흐르는 우주의 질서를 보여주고 있습니다. \n특히, 이번 북토크에서는 2014년 10월, 제주도를 방문한 웨인 레빈의 짧은 여정을 소개하였습니다. 그 여정에 함께한 닻프레스의 프로젝트 매니저, 북메이커가 토크를 진행하며, 여행에서의 비하인드 스토리와 웨인 레빈의 사진과 그의 예술가적 태도에 대한 이야기를 전해주었습니다. 제주를 담은 그의 사진은 닻미술관에서 전시 <섬 Islands, Jeju>를 통해 소개되었으며, 섬에서 섬으로 온 이방인의 카메라에 담긴 아티스트 북 「Island, Jeju」로 출간되었습니다. ",
    images: [
      "/Event/36/01.jpg",
      "/Event/36/02.jpg",
      "/Event/36/03.jpg",
      "/Event/36/04.jpg",
      "/Event/36/05.jpg",
      "/Event/36/06.jpg",
      "/Event/36/07.jpg",
      "/Event/36/08.jpg",
    ],
  },
  {
    id: 37,
    type: "Artist Talk / Lecture",
    date: "2014.10.17",
    place_en: "Friday Night Lecture, D’Ark Room",
    title_en: "FNL#1 Artist Talk: Wayne Levin, Barbara Bosworth",
    body_en: "",
    place_ko: "Friday Night Lecture, D’Ark Room",
    title_ko: "FNL#1 아티스트 토크: 웨인 레빈, 바바라 보스워스",
    body_ko:
      "지난 10월 17일 닻프레스 다크룸의 첫번째 Friday Night Lecture 아티스트 토크가 있었습니다. 간단한 오프닝 행사과 함께 깃 6호의 두 참여작가인 바바라 보스워스와 웨인 레빈의 렉쳐가 진행되었습니다. 자연 속에서 휴머니즘을 둘러싼 경이로운 순간들을 담아내는 두 예술가의 생생한 경험담과 함께 그들의 작업세계를 깊이 들여다 볼 수 있었던 뜻 깊은 시간이었습니다. 이번 시간에는 특별히 닻프레스에서 출판한 두 작가의 작품집을 함께 소개하며 관객과 심도 깊은 대화의 시간을 가졌습니다.\n \n참여작가: 웨인 레빈, 바바라 보스워스",
    images: [
      "/Event/37/01.jpg",
      "/Event/37/02.jpg",
      "/Event/37/03.jpg",
      "/Event/37/04.jpg",
      "/Event/37/05.jpg",
      "/Event/37/06.jpg",
      "/Event/37/07.jpg",
      "/Event/37/08.jpg",
      "/Event/37/09.jpg",
      "/Event/37/10.jpg",
      "/Event/37/11.jpg",
      "/Event/37/12.jpg",
      "/Event/37/13.jpg",
      "/Event/37/14.jpg",
      "/Event/37/15.jpg",
      "/Event/37/16.jpg",
      "/Event/37/17.jpg",
    ],
  },
];
export type Event = typeof events[0];
