name: CI-Firebase-hosting
description: 'build create-react-app SPA and deploy to the firebase hosting.'
author: 'iamswain25'

on:
  push:
    branches:
      - master

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN : ${{ secrets.FIREBASE_TOKEN }}